name: flame_simple_platformer
description: A 2d platformer made using Flame engine

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flame: 1.8.1
  flame_tiled: 1.12.0
  tiled: 0.10.1
  flame_audio: 2.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tiles/
    - assets/audio/
